name: Build

on: push

jobs:
  build-focal:
    name: Build with Ubuntu 20.04 and ROS Noetic
    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:noetic-desktop-full

    steps:
      - name: Create Catkin Workspace
        run: |
          source /opt/ros/noetic/setup.bash
          pwd
          mkdir catkin_ws
          cd catkin_ws
          mkdir src
          catkin_init
          cd src
      - name: Checkout code
        uses: actions/checkout@v2

