name: Build

on: push

jobs:
  build-focal:
    name: Build with Ubuntu 20.04 and ROS Noetic
    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:noetic-desktop-full

    env:
       CI_SOURCE_PATH: $(pwd)
       
    steps:
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y libeigen3-dev libsuitesparse-dev protobuf-compiler libnlopt-dev ros-noetic-octomap ros-noetic-octomap-ros libatlas-base-dev python3-matplotlib python3-numpy git
         
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
        
      - name: Build code
        run: |
          bash
          sh /opt/ros/noetic/setup.sh 
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws
          catkin_make
          sh devel/setup.sh
          cd ~/catkin_ws/src
          ln -s $CI_SOURCE_PATH
          cd ..
          catkin_make

