name: Build

on: push

jobs:
  build-focal:
    name: Build with Ubuntu 20.04 and ROS Noetic
    runs-on: ubuntu-latest
    
    container:
      image: osrf/ros:noetic-desktop-full

    steps:
      - name: Create Catkin Workspace
        run: |
          apt-get update
          apt-get install libeigen3-dev libsuitesparse-dev protobuf-compiler libnlopt-dev ros-noetic-octomap ros-noetic-octomap-ros libatlas-base-dev python3-matplotlib python3-numpy
          bash /opt/ros/noetic/setup.bash
          pwd
          mkdir catkin_ws
          cd catkin_ws
          mkdir src
          catkin_init_workspace
          cd src
          pwd
      - name: Checkout code
        uses: actions/checkout@v2

